### ISSUE TITLE
内网穿透报错

### ISSUE THREAD

**Issue by haoyuan-sjtu** [Van-wise/sd-colab#8]
Hey friends, I can't start up fcoooucs model by Ngrok
![666](https://github.com/Van-wise/sd-colab/assets/149029142/d6bd8913-6b2f-4548-ab6c-c71da472f0b0)
您好，fcoooucs案例中，Ngrok内网穿透工具报错
![777](https://github.com/Van-wise/sd-colab/assets/149029142/22e21c00-d56b-4c28-a41d-d1823d00cace)
请问您是否能给予些建议~

**Comment by Van-wise** [comment]
![微信截图_20231215100054](https://github.com/Van-wise/sd-colab/assets/118850813/7f8398b6-d247-4384-83bd-110c9e96151b)
You need to get ngrok token.：https://dashboard.ngrok.com/get-started/your-authtoken

**Comment by haoyuan-sjtu** [comment]
Thank you
